version: '2.4'

services:
  device_library_test:
    image: device_library_test:latest
    container_name: device_library_test
    privileged: true
    stdin_open: true
    tty: true
    restart: "no"
    volumes:
      - ./reports/:/reports/
      - /etc/board:/etc/board
      - /usr/lib/Advantech/:/usr/lib/Advantech/:ro
      - /lib/libSUSI-4.00.so:/lib/libSUSI-4.00.so:ro
      - /lib/libSUSI-4.00.so.1:/lib/libSUSI-4.00.so.1:ro
      - /lib/libSUSI-4.00.so.1.0.0:/lib/libSUSI-4.00.so.1.0.0:ro
      - /lib/libjansson.a:/lib/libjansson.a:ro
      - /lib/libjansson.so:/lib/libjansson.so:ro
      - /lib/libjansson.so.4:/lib/libjansson.so.4:ro
      - /lib/libjansson.so.4.11.0:/lib/libjansson.so.4.11.0:ro
      - /lib/libSusiIoT.so:/lib/libSusiIoT.so:ro
      - /lib/libSusiIoT.so.1.0.0:/lib/libSusiIoT.so.1.0.0:ro