services:
  device_library_test:
    image: ${IMAGE}
    container_name: device_library_test
    privileged: true
    stdin_open: true
    tty: true
    restart: "no"
    command: ["/app/container-run_test.sh"]
    environment:
      - AZDO_PAT=${AZDO_PAT}
      - AZDO_ARTIFACTS_FEED_NAME=${AZDO_ARTIFACTS_FEED_NAME}
      - AZDO_ARTIFACTS_FEED_URL=${AZDO_ARTIFACTS_FEED_URL}
      - AZDO_ARTIFACTS_FEED_NUGET_SOURCE_URL=${AZDO_ARTIFACTS_FEED_NUGET_SOURCE_URL}
      - NUGET_PKG_TO_BE_TESTED=${NUGET_PKG_TO_BE_TESTED}
      - USE_LOCAL_NUGET_SOURCE=${USE_LOCAL_NUGET_SOURCE}
      - NUGET_PKG_RESOLVED_BY_LOCAL_SOURCE=${NUGET_PKG_RESOLVED_BY_LOCAL_SOURCE}
      - NUGET_PKG_PATH_RESOLVED_BY_LOCAL_SOURCE=${NUGET_PKG_PATH_RESOLVED_BY_LOCAL_SOURCE}
      - BYPASS_ADVANCED_TEST=${BYPASS_ADVANCED_TEST}
    volumes:
      # ==================
      # Test Reports & Source Code
      # ==================
      - ./reports/:/reports/
      - ./src/TestToolProcess:/app/TestToolProcess
      - ./src/container-run_test.sh:/app/container-run_test.sh

      # ==================
      # Platform Resources
      # ==================
      - /usr/src/advantech:/usr/src/advantech:ro
      - /dev:/dev
      - /lib/x86_64-linux-gnu/:/lib/x86_64-linux-gnu/:ro
      - /usr/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/:ro

      # ==================
      # EApi Platform Libraries
      # ==================
      - /usr/lib/libATAuxIO.so:/usr/lib/libATAuxIO.so:ro
      - /usr/lib/libATGPIO.so:/usr/lib/libATGPIO.so:ro
      - /usr/lib/libBoardResource.so:/usr/lib/libBoardResource.so:ro
      - /usr/lib/libEAPI-IPS.so:/usr/lib/libEAPI-IPS.so:ro
      - /usr/lib/libEAPI.so:/usr/lib/libEAPI.so:ro
      - /usr/lib/libECGPIO.so:/usr/lib/libECGPIO.so:ro
      - /usr/lib/libATSMBUS.so:/usr/lib/libATSMBUS.so:ro
